name: pyscreener
channels:
  - omnia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - boost=1.74.0=py36h6957fcd_0
  - boost-cpp=1.74.0=h9359b55_0
  - bzip2=1.0.8=h516909a_3
  - ca-certificates=2020.6.20=hecda079_0
  - cairo=1.16.0=h3fc0475_1005
  - certifi=2020.6.20=py36h9f0ad1d_0
  - configargparse=1.2.3=pyh9f0ad1d_0
  - cython=0.29.21=py36h831f99a_0
  - fftw3f=3.3.4=2
  - fontconfig=2.13.1=h1056068_1002
  - freetype=2.10.2=he06d7ca_0
  - glib=2.65.0=h3eb4bd4_0
  - h5py=2.10.0=nompi_py36hecadee3_104
  - hdf5=1.10.6=nompi_h3c11f04_101
  - icu=67.1=he1b5a44_0
  - importlib-metadata=2.0.0=py36h9f0ad1d_0
  - importlib_metadata=2.0.0=0
  - importlib_resources=3.0.0=py36h9f0ad1d_0
  - joblib=0.16.0=py_0
  - jpeg=9d=h516909a_0
  - lcms2=2.11=hbd6801e_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libblas=3.8.0=17_openblas
  - libcblas=3.8.0=17_openblas
  - libedit=3.1.20191231=h14c3975_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.5.0=hdf63c60_16
  - libiconv=1.16=h516909a_0
  - liblapack=3.8.0=17_openblas
  - libopenblas=0.3.10=pthreads_hb3c22a3_4
  - libpng=1.6.37=hed695b0_2
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=hc7e4089_6
  - libuuid=2.32.1=h14c3975_1000
  - libwebp-base=1.1.0=h516909a_3
  - libxcb=1.13=h14c3975_1002
  - libxml2=2.9.10=h68273f3_2
  - lz4-c=1.9.2=he1b5a44_3
  - mpi=1.0=mpich
  - mpi4py=3.0.3=py36h094ef99_1
  - mpich=3.3.2=hc856adb_0
  - ncurses=6.2=he6710b0_1
  - numpy=1.19.1=py36h3849536_2
  - olefile=0.46=py_0
  - openmm=7.4.2=py36_cuda101_rc_1
  - openssl=1.1.1h=h516909a_0
  - pandas=1.1.2=py36h831f99a_0
  - pcre=8.44=he1b5a44_0
  - pdbfixer=1.6=py36_0
  - pillow=7.2.0=py36h8328e55_1
  - pip=20.2.2=py36_0
  - pixman=0.38.0=h516909a_1003
  - plotly=4.10.0=pyh9f0ad1d_0
  - pthread-stubs=0.4=h14c3975_1001
  - pycairo=1.19.1=py36h4779a57_3
  - python=3.6.12=hcff3b4d_2
  - python-dateutil=2.8.1=py_0
  - python_abi=3.6=1_cp36m
  - pytz=2020.1=pyh9f0ad1d_0
  - rdkit=2020.03.6=py36hf6a1616_0
  - readline=8.0=h7b6447c_0
  - retrying=1.3.3=py_2
  - scikit-learn=0.23.2=py36hfb379a7_0
  - scipy=1.5.2=py36h3a855aa_0
  - setuptools=49.6.0=py36_1
  - six=1.15.0=pyh9f0ad1d_0
  - sqlite=3.33.0=h62c20be_0
  - threadpoolctl=2.1.0=pyh5ca1d4c_0
  - tk=8.6.10=hbc83047_0
  - tqdm=4.50.0=pyh9f0ad1d_0
  - wheel=0.35.1=py_0
  - xorg-kbproto=1.0.7=h14c3975_1002
  - xorg-libice=1.0.10=h516909a_0
  - xorg-libsm=1.2.3=h84519dc_1000
  - xorg-libx11=1.6.12=h516909a_0
  - xorg-libxau=1.0.9=h14c3975_0
  - xorg-libxdmcp=1.1.3=h516909a_0
  - xorg-libxext=1.3.4=h516909a_0
  - xorg-libxrender=0.9.10=h516909a_1002
  - xorg-renderproto=0.11.1=h14c3975_1002
  - xorg-xextproto=7.3.0=h14c3975_1002
  - xorg-xproto=7.0.31=h14c3975_1007
  - xz=5.2.5=h7b6447c_0
  - zipp=3.2.0=py_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.5=h6597ccf_2
